//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Cabfind.DespatchManager.AurigaWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BookingServiceSoap12SoapBinding", Namespace="http://auriga.co.uk/")]
    public partial class BookingService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindStatusExtendedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStatusExtendedOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBookingOperationCompleted;
        
        private System.Threading.SendOrPostCallback BookOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback PayOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifyAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifyAccount2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPreferenceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BookingService() {
            this.Url = global::Cabfind.DespatchManager.Properties.Settings.Default.Cabfind_DespatchManager_AurigaWS_BookingService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event LogoutCompletedEventHandler LogoutCompleted;
        
        /// <remarks/>
        public event GetStatusCompletedEventHandler GetStatusCompleted;
        
        /// <remarks/>
        public event FindStatusExtendedCompletedEventHandler FindStatusExtendedCompleted;
        
        /// <remarks/>
        public event GetStatusExtendedCompletedEventHandler GetStatusExtendedCompleted;
        
        /// <remarks/>
        public event CancelCompletedEventHandler CancelCompleted;
        
        /// <remarks/>
        public event GetBookingCompletedEventHandler GetBookingCompleted;
        
        /// <remarks/>
        public event BookCompletedEventHandler BookCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event PayCompletedEventHandler PayCompleted;
        
        /// <remarks/>
        public event VerifyAccountCompletedEventHandler VerifyAccountCompleted;
        
        /// <remarks/>
        public event VerifyAccount2CompletedEventHandler VerifyAccount2Completed;
        
        /// <remarks/>
        public event GetPreferenceCompletedEventHandler GetPreferenceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://auriga.co.uk/Login", RequestNamespace="http://auriga.co.uk/", ResponseNamespace="http://auriga.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Login(string userName, string userPassword, string userPartner) {
            object[] results = this.Invoke("Login", new object[] {
                        userName,
                        userPassword,
                        userPartner});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string userName, string userPassword, string userPartner) {
            this.LoginAsync(userName, userPassword, userPartner, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string userName, string userPassword, string userPartner, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        userName,
                        userPassword,
                        userPartner}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://auriga.co.uk/Logout", RequestNamespace="http://auriga.co.uk/", ResponseNamespace="http://auriga.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Logout() {
            this.Invoke("Logout", new object[0]);
        }
        
        /// <remarks/>
        public void LogoutAsync() {
            this.LogoutAsync(null);
        }
        
        /// <remarks/>
        public void LogoutAsync(object userState) {
            if ((this.LogoutOperationCompleted == null)) {
                this.LogoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogoutOperationCompleted);
            }
            this.InvokeAsync("Logout", new object[0], this.LogoutOperationCompleted, userState);
        }
        
        private void OnLogoutOperationCompleted(object arg) {
            if ((this.LogoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogoutCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://auriga.co.uk/GetStatus", RequestNamespace="http://auriga.co.uk/", ResponseNamespace="http://auriga.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BookingStatus GetStatus(string bookingId) {
            object[] results = this.Invoke("GetStatus", new object[] {
                        bookingId});
            return ((BookingStatus)(results[0]));
        }
        
        /// <remarks/>
        public void GetStatusAsync(string bookingId) {
            this.GetStatusAsync(bookingId, null);
        }
        
        /// <remarks/>
        public void GetStatusAsync(string bookingId, object userState) {
            if ((this.GetStatusOperationCompleted == null)) {
                this.GetStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStatusOperationCompleted);
            }
            this.InvokeAsync("GetStatus", new object[] {
                        bookingId}, this.GetStatusOperationCompleted, userState);
        }
        
        private void OnGetStatusOperationCompleted(object arg) {
            if ((this.GetStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStatusCompleted(this, new GetStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://auriga.co.uk/FindStatusExtended", RequestNamespace="http://auriga.co.uk/", ResponseNamespace="http://auriga.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("FindStatusExtendedResult")]
        public BookingStatusExtended[] FindStatusExtended(System.DateTime start, System.DateTime finish, string customerReference, [System.Xml.Serialization.XmlElementAttribute("bookingStatus")] BookingStatus[] bookingStatus, int offset) {
            object[] results = this.Invoke("FindStatusExtended", new object[] {
                        start,
                        finish,
                        customerReference,
                        bookingStatus,
                        offset});
            return ((BookingStatusExtended[])(results[0]));
        }
        
        /// <remarks/>
        public void FindStatusExtendedAsync(System.DateTime start, System.DateTime finish, string customerReference, BookingStatus[] bookingStatus, int offset) {
            this.FindStatusExtendedAsync(start, finish, customerReference, bookingStatus, offset, null);
        }
        
        /// <remarks/>
        public void FindStatusExtendedAsync(System.DateTime start, System.DateTime finish, string customerReference, BookingStatus[] bookingStatus, int offset, object userState) {
            if ((this.FindStatusExtendedOperationCompleted == null)) {
                this.FindStatusExtendedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindStatusExtendedOperationCompleted);
            }
            this.InvokeAsync("FindStatusExtended", new object[] {
                        start,
                        finish,
                        customerReference,
                        bookingStatus,
                        offset}, this.FindStatusExtendedOperationCompleted, userState);
        }
        
        private void OnFindStatusExtendedOperationCompleted(object arg) {
            if ((this.FindStatusExtendedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindStatusExtendedCompleted(this, new FindStatusExtendedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://auriga.co.uk/GetStatusExtended", RequestNamespace="http://auriga.co.uk/", ResponseNamespace="http://auriga.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BookingStatusExtended GetStatusExtended(string bookingId) {
            object[] results = this.Invoke("GetStatusExtended", new object[] {
                        bookingId});
            return ((BookingStatusExtended)(results[0]));
        }
        
        /// <remarks/>
        public void GetStatusExtendedAsync(string bookingId) {
            this.GetStatusExtendedAsync(bookingId, null);
        }
        
        /// <remarks/>
        public void GetStatusExtendedAsync(string bookingId, object userState) {
            if ((this.GetStatusExtendedOperationCompleted == null)) {
                this.GetStatusExtendedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStatusExtendedOperationCompleted);
            }
            this.InvokeAsync("GetStatusExtended", new object[] {
                        bookingId}, this.GetStatusExtendedOperationCompleted, userState);
        }
        
        private void OnGetStatusExtendedOperationCompleted(object arg) {
            if ((this.GetStatusExtendedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStatusExtendedCompleted(this, new GetStatusExtendedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://auriga.co.uk/Cancel", RequestNamespace="http://auriga.co.uk/", ResponseNamespace="http://auriga.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BookingStatus Cancel(string bookingId) {
            object[] results = this.Invoke("Cancel", new object[] {
                        bookingId});
            return ((BookingStatus)(results[0]));
        }
        
        /// <remarks/>
        public void CancelAsync(string bookingId) {
            this.CancelAsync(bookingId, null);
        }
        
        /// <remarks/>
        public void CancelAsync(string bookingId, object userState) {
            if ((this.CancelOperationCompleted == null)) {
                this.CancelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelOperationCompleted);
            }
            this.InvokeAsync("Cancel", new object[] {
                        bookingId}, this.CancelOperationCompleted, userState);
        }
        
        private void OnCancelOperationCompleted(object arg) {
            if ((this.CancelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelCompleted(this, new CancelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://auriga.co.uk/GetBooking", RequestNamespace="http://auriga.co.uk/", ResponseNamespace="http://auriga.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Booking GetBooking(string bookingId) {
            object[] results = this.Invoke("GetBooking", new object[] {
                        bookingId});
            return ((Booking)(results[0]));
        }
        
        /// <remarks/>
        public void GetBookingAsync(string bookingId) {
            this.GetBookingAsync(bookingId, null);
        }
        
        /// <remarks/>
        public void GetBookingAsync(string bookingId, object userState) {
            if ((this.GetBookingOperationCompleted == null)) {
                this.GetBookingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBookingOperationCompleted);
            }
            this.InvokeAsync("GetBooking", new object[] {
                        bookingId}, this.GetBookingOperationCompleted, userState);
        }
        
        private void OnGetBookingOperationCompleted(object arg) {
            if ((this.GetBookingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBookingCompleted(this, new GetBookingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://auriga.co.uk/Book", RequestNamespace="http://auriga.co.uk/", ResponseNamespace="http://auriga.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("BookResult")]
        public BookingResult[] Book(Booking newBooking) {
            object[] results = this.Invoke("Book", new object[] {
                        newBooking});
            return ((BookingResult[])(results[0]));
        }
        
        /// <remarks/>
        public void BookAsync(Booking newBooking) {
            this.BookAsync(newBooking, null);
        }
        
        /// <remarks/>
        public void BookAsync(Booking newBooking, object userState) {
            if ((this.BookOperationCompleted == null)) {
                this.BookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBookOperationCompleted);
            }
            this.InvokeAsync("Book", new object[] {
                        newBooking}, this.BookOperationCompleted, userState);
        }
        
        private void OnBookOperationCompleted(object arg) {
            if ((this.BookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BookCompleted(this, new BookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://auriga.co.uk/Update", RequestNamespace="http://auriga.co.uk/", ResponseNamespace="http://auriga.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BookingResult Update(string bookingId, Booking modifiedBooking) {
            object[] results = this.Invoke("Update", new object[] {
                        bookingId,
                        modifiedBooking});
            return ((BookingResult)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(string bookingId, Booking modifiedBooking) {
            this.UpdateAsync(bookingId, modifiedBooking, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(string bookingId, Booking modifiedBooking, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        bookingId,
                        modifiedBooking}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://auriga.co.uk/Pay", RequestNamespace="http://auriga.co.uk/", ResponseNamespace="http://auriga.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PaymentResult Pay(string bookingId, Payment cardPayment) {
            object[] results = this.Invoke("Pay", new object[] {
                        bookingId,
                        cardPayment});
            return ((PaymentResult)(results[0]));
        }
        
        /// <remarks/>
        public void PayAsync(string bookingId, Payment cardPayment) {
            this.PayAsync(bookingId, cardPayment, null);
        }
        
        /// <remarks/>
        public void PayAsync(string bookingId, Payment cardPayment, object userState) {
            if ((this.PayOperationCompleted == null)) {
                this.PayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPayOperationCompleted);
            }
            this.InvokeAsync("Pay", new object[] {
                        bookingId,
                        cardPayment}, this.PayOperationCompleted, userState);
        }
        
        private void OnPayOperationCompleted(object arg) {
            if ((this.PayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PayCompleted(this, new PayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://auriga.co.uk/VerifyAccount", RequestNamespace="http://auriga.co.uk/", ResponseNamespace="http://auriga.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VerifyAccountResult VerifyAccount(string accountName, string accountPassword, string profileEmailAddress) {
            object[] results = this.Invoke("VerifyAccount", new object[] {
                        accountName,
                        accountPassword,
                        profileEmailAddress});
            return ((VerifyAccountResult)(results[0]));
        }
        
        /// <remarks/>
        public void VerifyAccountAsync(string accountName, string accountPassword, string profileEmailAddress) {
            this.VerifyAccountAsync(accountName, accountPassword, profileEmailAddress, null);
        }
        
        /// <remarks/>
        public void VerifyAccountAsync(string accountName, string accountPassword, string profileEmailAddress, object userState) {
            if ((this.VerifyAccountOperationCompleted == null)) {
                this.VerifyAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyAccountOperationCompleted);
            }
            this.InvokeAsync("VerifyAccount", new object[] {
                        accountName,
                        accountPassword,
                        profileEmailAddress}, this.VerifyAccountOperationCompleted, userState);
        }
        
        private void OnVerifyAccountOperationCompleted(object arg) {
            if ((this.VerifyAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyAccountCompleted(this, new VerifyAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://auriga.co.uk/VerifyAccount2", RequestNamespace="http://auriga.co.uk/", ResponseNamespace="http://auriga.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VerifyAccount2Result VerifyAccount2(string accountName, string accountNumber, string accountPassword, string profileEmailAddress) {
            object[] results = this.Invoke("VerifyAccount2", new object[] {
                        accountName,
                        accountNumber,
                        accountPassword,
                        profileEmailAddress});
            return ((VerifyAccount2Result)(results[0]));
        }
        
        /// <remarks/>
        public void VerifyAccount2Async(string accountName, string accountNumber, string accountPassword, string profileEmailAddress) {
            this.VerifyAccount2Async(accountName, accountNumber, accountPassword, profileEmailAddress, null);
        }
        
        /// <remarks/>
        public void VerifyAccount2Async(string accountName, string accountNumber, string accountPassword, string profileEmailAddress, object userState) {
            if ((this.VerifyAccount2OperationCompleted == null)) {
                this.VerifyAccount2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyAccount2OperationCompleted);
            }
            this.InvokeAsync("VerifyAccount2", new object[] {
                        accountName,
                        accountNumber,
                        accountPassword,
                        profileEmailAddress}, this.VerifyAccount2OperationCompleted, userState);
        }
        
        private void OnVerifyAccount2OperationCompleted(object arg) {
            if ((this.VerifyAccount2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyAccount2Completed(this, new VerifyAccount2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://auriga.co.uk/GetPreference", RequestNamespace="http://auriga.co.uk/", ResponseNamespace="http://auriga.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetPreferenceResult GetPreference() {
            object[] results = this.Invoke("GetPreference", new object[0]);
            return ((GetPreferenceResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetPreferenceAsync() {
            this.GetPreferenceAsync(null);
        }
        
        /// <remarks/>
        public void GetPreferenceAsync(object userState) {
            if ((this.GetPreferenceOperationCompleted == null)) {
                this.GetPreferenceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPreferenceOperationCompleted);
            }
            this.InvokeAsync("GetPreference", new object[0], this.GetPreferenceOperationCompleted, userState);
        }
        
        private void OnGetPreferenceOperationCompleted(object arg) {
            if ((this.GetPreferenceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPreferenceCompleted(this, new GetPreferenceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public void CancelAsync1(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://auriga.co.uk/")]
    public enum BookingStatus {
        
        /// <remarks/>
        UNKNOWN,
        
        /// <remarks/>
        BOOKED,
        
        /// <remarks/>
        DESPATCHED,
        
        /// <remarks/>
        DONE,
        
        /// <remarks/>
        CANCELLED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://auriga.co.uk/")]
    public partial class BookingStatusExtended {
        
        private string idField;
        
        private BookingStatus statusField;
        
        private VehicleInformation vehicleField;
        
        private System.DateTime lastUpdateTimeField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public BookingStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public VehicleInformation vehicle {
            get {
                return this.vehicleField;
            }
            set {
                this.vehicleField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime lastUpdateTime {
            get {
                return this.lastUpdateTimeField;
            }
            set {
                this.lastUpdateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://auriga.co.uk/")]
    public partial class VehicleInformation {
        
        private Position positionField;
        
        private string vehicleDescriptionField;
        
        private string driverDescriptionField;
        
        /// <remarks/>
        public Position position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public string vehicleDescription {
            get {
                return this.vehicleDescriptionField;
            }
            set {
                this.vehicleDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string driverDescription {
            get {
                return this.driverDescriptionField;
            }
            set {
                this.driverDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://auriga.co.uk/")]
    public partial class Position {
        
        private double latitudeField;
        
        private double longitudeField;
        
        /// <remarks/>
        public double latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public double longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://auriga.co.uk/")]
    public partial class PreferenceError {
        
        private int codeField;
        
        private string messageField;
        
        /// <remarks/>
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://auriga.co.uk/")]
    public partial class GetPreferenceResult {
        
        private bool successField;
        
        private PreferenceError errorField;
        
        private string[] preferenceField;
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public PreferenceError error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public string[] preference {
            get {
                return this.preferenceField;
            }
            set {
                this.preferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://auriga.co.uk/")]
    public partial class VerifyAccount2Result {
        
        private bool successField;
        
        private AccountError errorField;
        
        private string accountNameField;
        
        private string profilePasswordField;
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public AccountError error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public string accountName {
            get {
                return this.accountNameField;
            }
            set {
                this.accountNameField = value;
            }
        }
        
        /// <remarks/>
        public string profilePassword {
            get {
                return this.profilePasswordField;
            }
            set {
                this.profilePasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://auriga.co.uk/")]
    public partial class AccountError {
        
        private int codeField;
        
        private string messageField;
        
        /// <remarks/>
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://auriga.co.uk/")]
    public partial class VerifyAccountResult {
        
        private bool successField;
        
        private AccountError errorField;
        
        private string profilePasswordField;
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public AccountError error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public string profilePassword {
            get {
                return this.profilePasswordField;
            }
            set {
                this.profilePasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://auriga.co.uk/")]
    public partial class PaymentResult {
        
        private PaymentOutcome outcomeField;
        
        private string authCodeField;
        
        /// <remarks/>
        public PaymentOutcome outcome {
            get {
                return this.outcomeField;
            }
            set {
                this.outcomeField = value;
            }
        }
        
        /// <remarks/>
        public string authCode {
            get {
                return this.authCodeField;
            }
            set {
                this.authCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://auriga.co.uk/")]
    public enum PaymentOutcome {
        
        /// <remarks/>
        DECLINED,
        
        /// <remarks/>
        ACCEPTED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://auriga.co.uk/")]
    public partial class BookingInformation {
        
        private string idField;
        
        private string jobNumberField;
        
        private BookingStatus statusField;
        
        private Price priceField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string jobNumber {
            get {
                return this.jobNumberField;
            }
            set {
                this.jobNumberField = value;
            }
        }
        
        /// <remarks/>
        public BookingStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public Price price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://auriga.co.uk/")]
    public partial class Price {
        
        private bool isFixedField;
        
        private double fareField;
        
        private float distanceField;
        
        /// <remarks/>
        public bool isFixed {
            get {
                return this.isFixedField;
            }
            set {
                this.isFixedField = value;
            }
        }
        
        /// <remarks/>
        public double fare {
            get {
                return this.fareField;
            }
            set {
                this.fareField = value;
            }
        }
        
        /// <remarks/>
        public float distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://auriga.co.uk/")]
    public partial class BookingError {
        
        private int codeField;
        
        private string messageField;
        
        /// <remarks/>
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://auriga.co.uk/")]
    public partial class BookingResult {
        
        private bool successField;
        
        private BookingError errorField;
        
        private BookingInformation informationField;
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public BookingError error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public BookingInformation information {
            get {
                return this.informationField;
            }
            set {
                this.informationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://auriga.co.uk/")]
    public partial class Payment {
        
        private string cardNumberField;
        
        private string expiryDateField;
        
        private string startDateField;
        
        private string issueNumberField;
        
        private string cssField;
        
        private Address cardHolderAddressField;
        
        private int amountField;
        
        private PaymentOutcome outcomeField;
        
        private string authCodeField;
        
        /// <remarks/>
        public string cardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
            }
        }
        
        /// <remarks/>
        public string expiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public string issueNumber {
            get {
                return this.issueNumberField;
            }
            set {
                this.issueNumberField = value;
            }
        }
        
        /// <remarks/>
        public string css {
            get {
                return this.cssField;
            }
            set {
                this.cssField = value;
            }
        }
        
        /// <remarks/>
        public Address cardHolderAddress {
            get {
                return this.cardHolderAddressField;
            }
            set {
                this.cardHolderAddressField = value;
            }
        }
        
        /// <remarks/>
        public int amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public PaymentOutcome outcome {
            get {
                return this.outcomeField;
            }
            set {
                this.outcomeField = value;
            }
        }
        
        /// <remarks/>
        public string authCode {
            get {
                return this.authCodeField;
            }
            set {
                this.authCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://auriga.co.uk/")]
    public partial class Address {
        
        private string buildingNameorNumberField;
        
        private string streetNameField;
        
        private string townOrDistrictField;
        
        private string postCodeField;
        
        private Position positionField;
        
        /// <remarks/>
        public string buildingNameorNumber {
            get {
                return this.buildingNameorNumberField;
            }
            set {
                this.buildingNameorNumberField = value;
            }
        }
        
        /// <remarks/>
        public string streetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
            }
        }
        
        /// <remarks/>
        public string townOrDistrict {
            get {
                return this.townOrDistrictField;
            }
            set {
                this.townOrDistrictField = value;
            }
        }
        
        /// <remarks/>
        public string postCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
            }
        }
        
        /// <remarks/>
        public Position position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://auriga.co.uk/")]
    public partial class Account {
        
        private string nameField;
        
        private string referenceField;
        
        private string passwordField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://auriga.co.uk/")]
    public partial class FlightInfo {
        
        private string identifierField;
        
        private string destinationField;
        
        private string timeField;
        
        /// <remarks/>
        public string identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        public string destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public string time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://auriga.co.uk/")]
    public partial class Contact {
        
        private string nameField;
        
        private string phoneField;
        
        private string emailField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://auriga.co.uk/")]
    public partial class Booking {
        
        private string idField;
        
        private string jobNumberField;
        
        private BookingStatus statusField;
        
        private System.DateTime pickupDateTimeField;
        
        private Contact passengerField;
        
        private Address[] addressesField;
        
        private FlightInfo flightInfoField;
        
        private string notesField;
        
        private int numberOfVehiclesField;
        
        private string[] preferencesField;
        
        private VehicleInformation vehicleField;
        
        private Price priceField;
        
        private PaymentType paymentTypeField;
        
        private Account accountField;
        
        private Payment paymentField;
        
        private string clientReferenceField;
        
        private string notificationField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string jobNumber {
            get {
                return this.jobNumberField;
            }
            set {
                this.jobNumberField = value;
            }
        }
        
        /// <remarks/>
        public BookingStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime pickupDateTime {
            get {
                return this.pickupDateTimeField;
            }
            set {
                this.pickupDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public Contact passenger {
            get {
                return this.passengerField;
            }
            set {
                this.passengerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public Address[] addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
            }
        }
        
        /// <remarks/>
        public FlightInfo flightInfo {
            get {
                return this.flightInfoField;
            }
            set {
                this.flightInfoField = value;
            }
        }
        
        /// <remarks/>
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        public int numberOfVehicles {
            get {
                return this.numberOfVehiclesField;
            }
            set {
                this.numberOfVehiclesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public string[] preferences {
            get {
                return this.preferencesField;
            }
            set {
                this.preferencesField = value;
            }
        }
        
        /// <remarks/>
        public VehicleInformation vehicle {
            get {
                return this.vehicleField;
            }
            set {
                this.vehicleField = value;
            }
        }
        
        /// <remarks/>
        public Price price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public PaymentType paymentType {
            get {
                return this.paymentTypeField;
            }
            set {
                this.paymentTypeField = value;
            }
        }
        
        /// <remarks/>
        public Account account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
        
        /// <remarks/>
        public Payment payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
            }
        }
        
        /// <remarks/>
        public string clientReference {
            get {
                return this.clientReferenceField;
            }
            set {
                this.clientReferenceField = value;
            }
        }
        
        /// <remarks/>
        public string notification {
            get {
                return this.notificationField;
            }
            set {
                this.notificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://auriga.co.uk/")]
    public enum PaymentType {
        
        /// <remarks/>
        CASH,
        
        /// <remarks/>
        ACCOUNT,
        
        /// <remarks/>
        CARD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void LogoutCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetStatusCompletedEventHandler(object sender, GetStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BookingStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BookingStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void FindStatusExtendedCompletedEventHandler(object sender, FindStatusExtendedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindStatusExtendedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindStatusExtendedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BookingStatusExtended[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BookingStatusExtended[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetStatusExtendedCompletedEventHandler(object sender, GetStatusExtendedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStatusExtendedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStatusExtendedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BookingStatusExtended Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BookingStatusExtended)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CancelCompletedEventHandler(object sender, CancelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BookingStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BookingStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetBookingCompletedEventHandler(object sender, GetBookingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBookingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBookingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Booking Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Booking)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void BookCompletedEventHandler(object sender, BookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BookingResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BookingResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BookingResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BookingResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void PayCompletedEventHandler(object sender, PayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PaymentResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PaymentResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void VerifyAccountCompletedEventHandler(object sender, VerifyAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifyAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VerifyAccountResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VerifyAccountResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void VerifyAccount2CompletedEventHandler(object sender, VerifyAccount2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyAccount2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifyAccount2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VerifyAccount2Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VerifyAccount2Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetPreferenceCompletedEventHandler(object sender, GetPreferenceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPreferenceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPreferenceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetPreferenceResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetPreferenceResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591